version: "3.8"

services:

  vanilla-background-service:
    build:
      dockerfile: dockerfile
      contet: .
    working_dir: /tmp/vanilla-background-service/
    volumes:
      - ./:/tmp/vanilla-background-service/
    tty: true

volumes:
  .:
